HomeAppliances/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('', include('apps.goods.urls', namespace='goods')),
    path('user/', include('apps.user.urls', namespace='user')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path("admin/", admin.site.urls),
]

apps/cart/urls.py
from django.urls import path
from .views import AddCartView, MyCartView

app_name = 'cart'

urlpatterns = [
    path('add', AddCartView.as_view(), name='add'),  # 加入购物车
    path('cart', MyCartView.as_view(), name='cart'),  # 购物车页面（显示购物车、增加商品、减少商品、删除商品）
]

apps/goods/urls.py
from django.urls import path
from .views import *

app_name = 'goods'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # 首页
    path('rotation', IndexView.index_rotation, name='rotation'),  # 首页轮播图
    path('goods/detail/<int:goods_sku_id>', GoodsDetailView.as_view(), name='detail'),  # 商品详情页
    path('goods/list/<str:show_type>/<int:page>', GoodsListView.as_view(), name='list'),  # 商品列表页
    path('goods/search/all/<int:page>', SearchView.as_view(), name='search'),  # 搜索页面
]

apps/order/urls.py
from django.urls import path
from .views import *


app_name = 'order'
urlpatterns = [
    path('order', OrderView.as_view(), name='order'),  # 订单页面（显示订单、提交订单）
    path('buy', NowBuyView.as_view(), name='buy'),  # 立即购买商品
    path('pay/<str:order_id>', PayView.as_view(), name='pay'),  # 支付页面
    path('pay/status/check', AliPayView.as_view(), name='check'),  # 支付结果查询
    path('payok/<str:order_id>', PayOkView.as_view(), name='payok'),  # 支付成功页面
    path('confirm', ConfirmReceiptView.as_view(), name='confirm'),  # 确认收货
    path('comment/<str:order_id>', GoodsCommentView.as_view(), name='comment')  # 订单评价
]

apps/user/urls.py
from django.urls import path
from .views import *

app_name = 'user'
urlpatterns = [
    path('', UserCenterView.as_view(), name='user'),  # 用户中心页
    path("login/", LoginView.as_view(), name='login'),  # 登录
    path("register", RegisterView.as_view(), name='register'),  # 注册
    path('send', SendCode.as_view(), name='send'),  # 发送注册码
    path('logout', LogoutView.as_view(), name='logout'),  # 退出登录
    path('banlance', BalanceView.as_view(), name='balance'),  # 用户余额
    path('address', AddressView.as_view(), name='address'),  # 用户地址
    path('modify_address', ModifyAddressView.as_view(), name='modify_address'),  # 改变地址
    path('my_order/<int:page>', UserOrderView.as_view(), name='my_order'),  # 我的订单
    path('order_detail/<str:order_id>', OrderDetailView.as_view(), name='order_detail'),  # 订单详情
    path('recharge', RechargeView.as_view(), name='recharge'),  # 充值
    path('upload_image', ModifyImageView.as_view(), name='image')  # 更换头像
]

templates/base_templates/action.html
<div id="orderaAction{{ order.order_id }}">
    <p class=" has-text-weight-bold pt-1 pb-1 has-text-right">共{{ order.total_count }}件商品，总金额{{ order.price }}元（含运费）</p>
    <div class=" buttons is-justify-content-end">
    {% if order.status == 1 %}
        <a class="button is-primary is-small" href="{% url 'order:pay' order.order_id %}">立即支付</a>
    {% elif order.status == 3 %}
        <button class="button is-primary is-small" @click="confirmProduct">确认收货</button>
    {% elif order.status == 4 and not order.is_commented %}
        <a class=" button is-primary is-small" href="{% url 'order:comment' order.order_id %}">立即评价</a>
    {% endif %}
    <a href="{% url 'user:order_detail' order.order_id %}" class="button is-small">订单详情</a>
    </div>
</div>

<script>
    var confirmAction = new Vue({
        el: '#orderaAction{{ order.order_id }}',
        delimiters: ['{$', '$}'],
        methods: {
            confirmProduct(){
                request({
                    url:'{% url "order:confirm" %}',
                    method: 'post',
                    data: {
                        order_id: {{ order.order_id }}
                    }
                }).then(res => {
                    if (res.data.status == 200) {
                        bayke.toastMessage('is-success', res.data.msg)
                        setTimeout(function(){location.reload()}, 2000)
                    }
                    else {
                        bayke.toastMessage('is-danger', res.data.errmsg)
                    }
                })
            }
        }
    })
</script>

templates/base_templates/banners.html
<div id="carousel" class="container">
    <template>
        <b-carousel>
            <b-carousel-item v-for="carousel in carousels">
                <section :class="`hero is-medium`">
                    <img width="100%" :src="`${carousel.img}`" :alt="carousel.desc">
                </section>
            </b-carousel-item>
        </b-carousel>
    </template>
</div>
<script>
    var carousel = new Vue({
        el: '#carousel',
        delimiters: ['{$', '$}'],
        created() {
            this.getBanners()
        },
        data: {
            carousels: []
        },
        methods: {
            getBanners(){
                fetch("{% url 'goods:rotation' %}").then(res => res.json()).then(data => {
                    this.carousels = data.data
                })
            }
        },
    })
</script>

templates/base_templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% block stylesheet %}{% static "css/buefy.min.css" %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialdesignicons.min.css' %}">
    <script src="{% static 'js/axios.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/vue.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/buefy.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/http.js' %}" type="text/javascript"></script>
    <link rel="shortcut icon" href="{% url 'media' 'img/logo.png' %}">
    {% block extrahead_script %}{% endblock extrahead_script %}
    {% block extrastyle %}{% endblock extrastyle %}
</head>
<body>

{# 头部信息 #}
{% block head_top %}
    <div id="head-top">{% include 'base_templates/head_top.html' %}</div>
{% endblock head_top %}

{# 导航栏 #}
{% block header %}
    <div id="header">{% include 'base_templates/navbar.html' %}</div>
{% endblock header %}

<div id="main" class="mb-3">
    {% block breadcrumb %}{% endblock breadcrumb %}
    {% block banners %}{% endblock banners %}
    <div class="container">
        {% block container %}{% endblock container %}
    </div>
</div>

{# 页脚 #}
<div id="footer">
    {% block footer %}
        {% include 'base_templates/footer.html' %}
    {% endblock %}
</div>

{% block vue %}{% endblock vue %}

{% if messages %}
    {% for message in messages %}
        <div id="notification">
            <b-notification
                    auto-close
                    {% if message.tags %}type="is-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} is-light"{% endif %}
                    :duration="3000"
                    has-icon
                    position="is-top-right"
                    aria-close-label="Close notification">
                {{ message }}
            </b-notification>
        </div>
    {% endfor %}
    <script>
        var notification = new Vue({
            el: '#notification',
            delimiters: ['{$', '$}'],
        })
    </script>
{% endif %}
</body>
</html>

templates/base_templates/base_address.html
<style>
    .add-box{ border: solid 1px rgb(224, 224, 224); height: 150px;}
    .add-box:hover{border-color: rgb(251, 59, 59); transition: ease .5s;}
    .add-box .btn-default{position: absolute;top: 0;right: 0;}
    .active{border-color: rgb(251, 59, 59);}
    .meng-box {display: none;}
    .add-box:hover .meng-box{
        display: block; 
        position: absolute;
        top:0; 
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(255, 255, 255, 0.755);
        transition: ease .5s;
    }
</style>

<div id="address">
    <div class="columns is-multiline">
        <div class="column is-3" v-for="addr in addressData" :key="addr.id">
            <b-loading :is-full-page="false" v-model="isLoading" :can-cancel="true"></b-loading>
            <div class="add-box is-clickable is-flex is-flex-direction-column is-align-items-start is-justify-content-center is-relative pl-5 pr-5"
                :class="{active: addr.is_default}" @click="pickAddress(addr)">

                {% if update or delete %}
                <div class="meng-box">
                    <div class=" buttons is-flex is-align-items-center is-justify-content-center" style="height:100%">
                        {% if update %}
                        <div class="button is-success is-light is-small" @click="updateAddress(addr)">
                            <span class="icon"><i class="mdi mdi-book-edit-outline"></i></span>
                            <span>编辑</span>
                        </div>
                        {% endif %}

                        {% if delete %}
                        <div class="button is-danger is-light is-small" @click="delAddress(addr.id)">
                            <span class="icon"><i class="mdi mdi-delete-alert-outline"></i></span>
                            <span>删除</span>
                        </div>
                        {% endif %}
                    </div>
                </div>
                {% endif %}

                <span class="tag is-danger btn-default is-radiusless" v-if="addr.is_default">{$ text $}</span>
                <h1 class="has-text-weight-bold">{$ addr.name $}</h1>
                <p>{$ addr.phone $}</p>
                <p>{$ addr.province $}{$ addr.city $}{$ addr.country $}{$ addr.address $}</p>
            </div>
        </div>
        <div class="column is-3">
            <div class="add-box is-clickable is-flex is-flex-direction-column is-align-items-center is-justify-content-center"
                @click="openModal">
                <span class="icon is-size-1 has-text-grey-light"><i class="mdi mdi-plus"></i></span>
                <p class="mt-3 has-text-grey-light">添加新地址</p>
            </div>
        </div>
    </div>
    <b-modal
        v-model="isComponentModalActive"
        has-modal-card
        :can-cancel="false">
        <modal-form v-bind="formProps"></modal-form>
    </b-modal>
</div>

<script>
    const ModalForm = {
        props: ['id', 'name', 'phone', 'email', 'province', 'city', 'country', 'address', 'is_default'],
        data(){
            return {
                labelPosition: 'on-border',
                formProps: {
                    'id': this.id || null,
                    'name': this.name || "",
                    'phone': this.phone || "",
                    'email': this.email || "",
                    'province': this.province || "",
                    'city': this.city || "",
                    'country': this.country || "",
                    'address': this.address || "",
                    'is_default': this.is_default || false
                }
            }
        },
        template: `
            <div class="modal-card" style="min-width: 200px">
                <header class="modal-card-head">
                    <p class="modal-card-title">收货地址</p>
                </header>
                <section class="modal-card-body">
                    <b-field label="收件人" :label-position="labelPosition">
                        <b-input
                            v-model="formProps.name"
                            type="text"
                            :value="formProps.name"
                            placeholder="Your name"
                            required>
                        </b-input>
                    </b-field>

                    <b-field label="手机号" :label-position="labelPosition">
                        <b-input
                            v-model="formProps.phone"
                            type="text"
                            :value="formProps.phone"
                            placeholder="Your phone"
                            :hasCounter="false"
                            :maxlength="11"
                            pattern="[1][3,4,5,7,8,9][0-9]{9}"
                            validation-message="手机号格式有误！"
                            required>
                        </b-input>
                    </b-field>
                    <b-field label="省份" :label-position="labelPosition">
                        <b-input
                            v-model="formProps.province"
                            type="text"
                            :value="formProps.province"
                            placeholder="Your province"
                            required>
                        </b-input>
                    </b-field>
                    <b-field label="城市" :label-position="labelPosition">
                        <b-input
                            v-model="formProps.city"
                            type="text"
                            :value="formProps.city"
                            placeholder="Your city"
                            required>
                        </b-input>
                    </b-field>
                    <b-field label="区/县" :label-position="labelPosition">
                        <b-input
                            v-model="formProps.country"
                            type="text"
                            :value="formProps.country"
                            placeholder="Your country"
                            required>
                        </b-input>
                    </b-field>
                    <b-field label="详细地址" :label-position="labelPosition">
                        <b-input
                            v-model="formProps.address"
                            type="text"
                            :value="formProps.address"
                            placeholder="Your address"
                            required>
                        </b-input>
                    </b-field>
                    <b-checkbox v-model="formProps.is_default" :value="formProps.is_default">设为默认</b-checkbox>
                </section>
                <footer class="modal-card-foot">
                    <b-button
                        label="取消"
                        @click="$parent.close()" />
                    <b-button
                        label="保存"
                        type="is-primary"
                        @click="save"/>
                </footer>
            </div>
        `,
        methods: {
            // 保存地址
            save(){
                let api = `{% url "user:modify_address" %}`
                let method = 'post'
                if (this.formProps.id) {
                    api = `{% url "user:modify_address" %}`
                    method = 'put'
                }
                // 数据库修改
                request({
                    method: method,
                    url: api,
                    headers: {'Accept': 'application/json'},
                    data: this.formProps
                }).then(res => {
                    if (res.data.status === 200) {
                        bayke.toastMessage('is-success', res.data.msg);
                        this.$parent.close()
                        location.reload()
                    }
                    else {
                        bayke.toastMessage('is-danger', res.data.errmsg)
                    }
                })
            },
        }
    }
</script>

<script>
    var address = new Vue({
        el: "#address",
        delimiters: ['{$', '$}'],
        components: {
            ModalForm
        },
        data: {
            addressData: [],
            text: "默认",
            isComponentModalActive: false,
            formProps: {},
            isLoading: false
        },
        created() {
            this.getAddress()
        },
        methods: {
            getAddress(){
                this.isLoading = true
                request({
                    url: '{% url "user:modify_address" %}',
                    method: 'get'
                }).then(res => {
                    res.data.data.forEach(el => {
                        this.addressData.push(el)
                        if (el.is_default){
                            this.formProps = el
                        }
                    })
                })
                this.isLoading = false
            },
            // 选择地址
            pickAddress(addr){
                this.formProps = addr;
                this.addressData.forEach(element => {
                    if (addr.id == element.id){
                        addr.is_default = true
                        this.text = "选择 ✔"
                    }else{
                        element.is_default = false
                    }
                })
            },

            // 修改地址
            updateAddress(addr){
                this.isComponentModalActive = true
                this.formProps = addr
            },

            // 新增地址弹窗
            openModal(){
                this.isComponentModalActive = true
                this.formProps = {}
            },

            // delAddress删除
            delAddress(id){
                this.$buefy.dialog.confirm({
                    message: '是否确认删除该地址！',
                    cancelText: '取消',
                    onConfirm: () => {
                        request({
                            method: 'delete',
                            url: `{% url "user:modify_address" %}`,
                            headers: {'Accept': 'application/json'},
                            data: id
                        }).then(res => {
                            if (res.data.status === 200) {
                                bayke.toastMessage('is-success', res.data.msg)
                                location.reload()
                            }
                            else {
                                bayke.toastMessage('is-danger', res.data.errmsg)
                            }
                        })
                    }
                })
            },
        }
    })
</script>

templates/base_templates/head_top.html
<div id="header-top" class="has-background-black-bis">
    <div class="is-flex is-justify-content-space-between is-align-items-center container" style="height:40px">
        <div class="head-top-left">
            {% block head_top_left %}
            欢迎您光临本店！
            {% endblock %}  
        </div>
        <div class="head-top-right">
            {% block head_top_right %}
            {% if request.user.is_authenticated %}
            <div class="dropdown is-hoverable usertools">
                <div class="dropdown-trigger">
                  <button class="button is-radiusless is-shadowless" aria-haspopup="true" aria-controls="dropdown-menu4" 
                    style="background: none; border:none">
                    <span>欢迎您，{{ request.user.username }}</span>
                    <span class="icon is-small">
                      <i class="mdi mdi-menu-down" aria-hidden="true"></i>
                    </span>
                  </button>
                </div>
                <div class="dropdown-menu" id="dropdown-menu4" role="menu" style="z-index:1000">
                  <div class="dropdown-content">
                    <a class="dropdown-item" href="{% url 'user:user' %}">
                        <span class="mdi mdi-account-box-outline"></span>
                        个人中心
                    </a>
                    <a class="dropdown-item" href="{% url 'user:my_order' 1 %}?sort=0">
                        <span class="mdi mdi-basket-plus-outline"></span>
                        我的订单
                    </a>
                    <div class=" dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'user:logout' %}">
                        <span class="mdi mdi-logout"></span>
                        退出
                    </a>
                  </div>
                </div>
            </div>
            {% else %}
            <a class="mr-2" href="{% url 'user:login' %}" target="_top">
                <span class="icon"><i class="mdi mdi-login"></i></span>
                登录
            </a> <span class="is-size-6">|</span>
            <a class="mr-3" href="{% url 'user:register' %}" target="_top">
                <span class="icon"><i class="mdi mdi-cash-register"></i></span>
                注册
            </a>
            {% endif %}
            <a class="cart" href="{% url 'cart:cart' %}" id="cart">
                <span class="icon"><i class="mdi mdi-cart-check"></i></span>
                <span id="cart_dynamic">购物车</span>
            </a>
            {% endblock %}
        </div>
    </div>
</div>
<script>
    var bayke = new Vue({
        el: '#cart',
        delimiters: ['{$', '$}'],
        data: {
           cartcount: 1
        },
        methods: {
            toastMessage(type, message){
                return this.$buefy.toast.open({
                    message: message,
                    type: type
                })
            },
        },
    })
</script>

templates/base_templates/navbar.html
<div id="navbar">
    <template>
        <b-navbar spaced shadow transparent wrapper-class="{% block navclass %}container{% endblock %}">
            <template #brand>
                <b-navbar-item tag="div">
                    {% block navbar_logo %}
                    <h1 class="is-size-4 has-text-weight-medium">家电之选</h1>
                    {% endblock %} 
                </b-navbar-item>
            </template>
            <template #start>
                {% block navbar_start %}
                <b-navbar-item href="{% url 'goods:index' %}">
                    首页
                </b-navbar-item>
                <b-navbar-item href="{% url 'goods:list' 'all' 1 %}">
                    全部分类
                </b-navbar-item>
                {% for goods_type in goods_types %}
                <b-navbar-dropdown label="{{ goods_type.name }}">
                    {% for name in goods_type.navs %}
                    <b-navbar-item href="#">
                        {{ name }}
                    </b-navbar-item>
                    {% endfor %}
                </b-navbar-dropdown>
                {% endfor %}
                {% endblock %}             
            </template>
            <template #end>
                {% block navbar_end %}
                <b-navbar-item tag="div">
                    <form action="{% url 'goods:search' 1 %}" method="get">
                        {% csrf_token %}
                        <div class="field-body">
                          <div class="field is-expanded">
                            <div class="field has-addons">
                              <p class="control is-expanded has-icons-left">
                                <input class="input" type="search" name="search" id="id_search" value="" placeholder="搜索心仪的商品吧！" maxlength="32">
                                <span class="icon is-left">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                              </p>
                              <p class="control has-icons-right">
                                <input class="button is-primary" type="submit" value="搜索">
                              </p>
                            </div>
                          </div>
                        </div>
                    </form>
                </b-navbar-item>
                {% endblock %} 
            </template>
        </b-navbar>
    </template>
</div>

<script>
    var navbar = new Vue({
        el: '#navbar',
        delimiters: ['{$', '$}']
    })
</script>

templates/base_templates/userinfo.html
<div class="column" id="userinfo">
    {{ userinfo|json_script:"baykeuserinfo-data" }}
    <div class="columns is-align-items-center is-marginless">
        <div class="column is-2 has-text-grey-light">用户名</div>
        <div class="column">{{ request.user.username }}</div>
    </div>
    <div class="dropdown-divider is-marginless"></div>

    <div class="columns is-align-items-center is-marginless">
        <div class="column is-2 has-text-grey-light">手机号</div>
        <div class="column is-flex is-justify-content-space-between is-align-items-center" id="phone">
            {% if userinfo.phone %}
                <p v-if="!editphone">{{ userinfo.phone }}</p>
            {% else %}
                <p v-if="!editphone">暂无手机号</p>
            {% endif %}
            <div>
                <b-input 
                    v-if="editphone" 
                    size="is-small" 
                    v-model="phone"
                    @blur="updateUserinfo('phone')">
                </b-input>
            </div> 
            <button class="button is-primary is-small is-outlined" @click="clickUserinfo('phone')">修改</button>
        </div>
    </div> 
    <div class="dropdown-divider is-marginless"></div>

    <div class="columns is-align-items-center is-marginless">
        <div class="column is-2 has-text-grey-light">邮箱</div>
        <div class="column is-flex is-justify-content-space-between is-align-items-center">
            <p v-if="!editemail">{{ userinfo.email }}</p>
            <div>
                <b-input type="email"
                    v-if="editemail"
                    size="is-small"
                    v-model="email"
                    :has-counter="false"
                    @blur="updateUserinfo('email')"
                    maxlength="30">
                </b-input>
            </div>
            <button class="button is-primary is-small is-outlined" @click="clickUserinfo('email')">修改</button>
        </div>
    </div>
    <div class="dropdown-divider is-marginless"></div>

    <div class="columns is-align-items-center is-marginless">
        <div class="column is-2 has-text-grey-light">余额</div>
        <div class="column is-flex is-justify-content-space-between is-align-items-center">
            <p>¥ {{ userinfo.balance }}</p>
            <p>
                <button class=" button is-primary is-light is-small" @click="recharge()" id="recharge">
                    <span class="icon"><i class="mdi mdi-credit-card-settings-outline"></i></span>
                    <span class="text">充值</span>
                </button>
            </p>
        </div>
    </div>
    <div class="dropdown-divider is-marginless"></div>

    <div class="columns is-align-items-center is-marginless">
        <div class="column is-2 has-text-grey-light">个人简介</div>
        <div class="column is-flex is-justify-content-space-between is-align-items-center">
            <p v-if="!editedesc">{{ userinfo.introduce }}</p>
            <div class=" is-flex-grow-1 mr-5">
                <b-input type="textarea"
                    v-if="editedesc"
                    size="is-small"
                    v-model="desc"
                    :has-counter="false"
                    @blur="updateUserinfo('desc')"
                    maxlength="150">
                </b-input>
            </div>
            <button class="button is-primary is-small is-outlined" @click="clickUserinfo('desc')">修改</button>

        </div>
    </div>
    <div class="dropdown-divider is-marginless"></div>
</div>
<script>
    var userinfo = new Vue({
        el: '#userinfo',
        delimiters: ['{$', '$}'],
        data: {
            editphone: false,
            editemail: false,
            editedesc: false
        },
        methods: {
            clickUserinfo(name){
                if (name == 'phone'){
                    this.editphone = true
                }else if (name == 'email'){
                    this.editemail = true
                }else if (name == 'desc'){
                    this.editedesc = true
                }
            },
            updateUserinfo(name){
                if (name == 'phone'){
                    this.editphone = false
                    if(!this.phone) {
                        bayke.toastMessage('is-danger', '内容不能为空');
                        return;
                    }
                    this.patchClientUserinfo({phone: this.phone})
                }else if (name == 'email'){
                    this.editemail = false
                    if(!this.email) {
                        bayke.toastMessage('is-danger', '内容不能为空');
                        return;
                    }
                    this.patchClientUserinfo({email: this.email})
                }else if (name == 'desc'){
                    this.editedesc = false
                    if(!this.desc) {
                        bayke.toastMessage('is-danger', '内容不能为空');
                        return;
                    }
                    this.patchClientUserinfo({introduce: this.desc})
                }
            },
            patchClientUserinfo(data){
                request({
                    url: '{% url "user:user" %}',
                    method: 'patch',
                    data: data
                }).then(res => {
                    if (res.data.status === 200){
                        bayke.toastMessage('is-success', '修改成功');
                        setTimeout(() => {
                            {#location.href = "{% url 'user:user' %}"#}
                            location.reload()
                        }, 2000);
                    }else {
                        if (!this.editphone){
                            this.editphone = true
                        }else if (!this.editemail){
                            this.editemail = true
                        }
                        bayke.toastMessage('is-danger', res.data.errmsg);
                    }
                })
            },
            recharge() {
                let result = confirm('请验证管理员身份');
                if(result) {
                     this.username = prompt('请输入管理员账号：');
                     this.password = prompt('请输入管理员密码：');
                     this.money = prompt('请输入要充值的数量（元）：');
                     request({
                        url: "{% url 'user:recharge' %}",
                        method: 'post',
                        data: {
                            username: this.username,
                            password: this.password,
                            money: this.money
                        }
                     }).then(res => {
                        if(res.data.status == 200) {
                            bayke.toastMessage('is-success', '充值成功');
                            setTimeout(() => {
                                location.href = "{% url 'user:user' %}"
                            }, 2000);
                        }
                        else {
                            bayke.toastMessage('is-danger', res.data.errmsg);
                        }
                    })
                }
            },

        },
    });
</script>