HomeAppliances/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('', include('apps.goods.urls', namespace='goods')),
    path('user/', include('apps.user.urls', namespace='user')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path("admin/", admin.site.urls),
]

apps/cart/urls.py
from django.urls import path
from .views import AddCartView, MyCartView

app_name = 'cart'

urlpatterns = [
    path('add', AddCartView.as_view(), name='add'),  # 加入购物车
    path('cart', MyCartView.as_view(), name='cart'),  # 购物车页面（显示购物车、增加商品、减少商品、删除商品）
]

apps/goods/urls.py
from django.urls import path
from .views import *

app_name = 'goods'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # 首页
    path('rotation', IndexView.index_rotation, name='rotation'),  # 首页轮播图
    path('goods/detail/<int:goods_sku_id>', GoodsDetailView.as_view(), name='detail'),  # 商品详情页
    path('goods/list/<str:show_type>/<int:page>', GoodsListView.as_view(), name='list'),  # 商品列表页
    path('goods/search/all/<int:page>', SearchView.as_view(), name='search'),  # 搜索页面
]

apps/order/urls.py
from django.urls import path
from .views import *


app_name = 'order'
urlpatterns = [
    path('order', OrderView.as_view(), name='order'),  # 订单页面（显示订单、提交订单）
    path('buy', NowBuyView.as_view(), name='buy'),  # 立即购买商品
    path('pay/<str:order_id>', PayView.as_view(), name='pay'),  # 支付页面
    path('pay/status/check', AliPayView.as_view(), name='check'),  # 支付结果查询
    path('payok/<str:order_id>', PayOkView.as_view(), name='payok'),  # 支付成功页面
    path('confirm', ConfirmReceiptView.as_view(), name='confirm'),  # 确认收货
    path('comment/<str:order_id>', GoodsCommentView.as_view(), name='comment')  # 订单评价
]

apps/goods/models.py
from django.db import models
from db.base_model import BaseModel


class GoodsImage(BaseModel):
    image = models.ImageField(upload_to='goods')  # 127.0.0.1:8000/media/goods/xx.png
    goods_dynamics = models.ForeignKey('GoodsDynamics', on_delete=models.CASCADE, verbose_name='商品名字')

    class Meta:
        verbose_name = '商品图片表'
        verbose_name_plural = verbose_name
        db_table = 'goods_image'

    def __str__(self):
        return self.goods_dynamics.goods_sku.name


class GoodsType(BaseModel):
    GOODS_TYPES = {
        0: 'all',
        1: 'intelligence',
        2: 'electricity',
        3: 'computer',
        4: 'headset',
    }

    name = models.CharField('类型名字', max_length=20)
    image = models.ImageField('图片', upload_to='goods_type')
    logo = models.CharField('类型标志', max_length=20, default='')

    class Meta:
        verbose_name = '商品类型表'
        verbose_name_plural = verbose_name
        db_table = 'goods_type'

    def __str__(self):
        return self.name


class GoodsSPU(BaseModel):
    name = models.CharField('SUP名字', max_length=30)
    detail = models.CharField('商品详情', max_length=50)
    goods_type = models.ForeignKey(GoodsType, on_delete=models.CASCADE, verbose_name='商品类型')

    class Meta:
        verbose_name = '商品SPU表'
        verbose_name_plural = verbose_name
        db_table = 'goods_spu'

    def __str__(self):
        return self.name


class GoodsSKU(BaseModel):
    GOODS_STATUS = (
        (0, '下架'),
        (1, '上架')
    )

    name = models.CharField('商品名字', max_length=50, null=False)
    status = models.BooleanField('商品状态', default=1, choices=GOODS_STATUS)
    goods_spu = models.ForeignKey(GoodsSPU, on_delete=models.CASCADE, verbose_name='商品SPU')
    goods_type = models.ForeignKey(GoodsType, on_delete=models.CASCADE, verbose_name='商品类型', default='')

    class Meta:
        verbose_name = '商品SKU表'
        verbose_name_plural = verbose_name
        db_table = 'goods_sku'

    def __str__(self):
        return self.name


class GoodsDynamics(BaseModel):
    price = models.DecimalField('价格', max_digits=11, decimal_places=2, null=False)
    stock = models.IntegerField('库存', null=False)
    color = models.CharField('颜色', max_length=10, null=True, default='')
    size = models.CharField('尺寸/大小', max_length=40, null=True, default='')
    sales = models.IntegerField('销量', null=False)
    goods_sku = models.ForeignKey(GoodsSKU, on_delete=models.CASCADE, verbose_name='商品SKU')

    class Meta:
        verbose_name = '商品动态表'
        verbose_name_plural = verbose_name
        db_table = 'goods_dynamics_table'

    def __str__(self):
        return self.goods_sku.name


class RotationCharts(BaseModel):
    ROTATION_CHOICE = (
        (0, '不轮播'),
        (1, '轮播')
    )

    name = models.CharField('名字', max_length=10)
    is_rotate = models.BooleanField('是否轮播', default=1, choices=ROTATION_CHOICE)
    image = models.ImageField('图片', upload_to='rotation')

    class Meta:
        verbose_name = '首页轮播图'
        verbose_name_plural = verbose_name
        db_table = 'rotation_image'

    def __str__(self):
        return self.name


class GoodsComment(BaseModel):
    SCORE_CHOICE = (
        (5, '好评'),
        (3, '中评'),
        (1, '差评')
    )
    from apps.order.models import GoodsOrder
    from ..user.models import MyUser
    content = models.CharField('评论内容', max_length=255)
    score = models.SmallIntegerField('评分', choices=SCORE_CHOICE, default=5)
    goods_order = models.ForeignKey(GoodsOrder, on_delete=models.CASCADE, verbose_name='商品订单', default='')
    goods_sku = models.ForeignKey(GoodsSKU, on_delete=models.CASCADE, verbose_name='商品sku', default='')
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, verbose_name='所属用户', default='')

    class Meta:
        verbose_name = '商品评价表'
        verbose_name_plural = verbose_name
        db_table = 'goods_comment'

    def __str__(self):
        return self.goods_sku.name

apps/goods/views.py
from django.shortcuts import render, reverse, redirect
from django.views import View
from django.core.cache import cache
from django.http import JsonResponse
from .models import GoodsType, GoodsSKU, GoodsDynamics, GoodsImage, RotationCharts


class BaseGoodsView(View):
    @staticmethod
    def get_navigation_info():
        """导航栏信息"""
        goods_types = cache.get('goods_types')

        if not goods_types:
            goods_types = GoodsType.objects.all()
            for goods_type in goods_types:
                sku = GoodsSKU.objects.filter(goods_type_id=goods_type.id)[:4]
                goods_type.navs = [s.goods_spu.name for s in sku]
            cache.set('goods_types', goods_types, 60 * 60 * 2)

        return goods_types

    @staticmethod
    def get_sku_image(goods_sku):
        """商品sku集对应的一张图片"""
        total_goods = []
        for goods in goods_sku:
            goods_dynamics = GoodsDynamics.objects.filter(goods_sku_id=goods.id)[0]
            image = GoodsImage.objects.filter(goods_dynamics_id=goods_dynamics.id)[0]
            goods_dynamics.image = image.image.url
            total_goods.append(goods_dynamics)

        return total_goods


class IndexView(BaseGoodsView):
    def get(self, request):
        context = cache.get('index_data')  # 从缓存中获取数据

        if not context:
            goods_types = GoodsType.objects.all()
            for goods_type in goods_types:
                sku = GoodsSKU.objects.filter(goods_type_id=goods_type.id).order_by('-update_time')[:4]
                goods_type.navs = [s.goods_spu.name for s in sku]

                goods_list = self.get_sku_image(sku)
                goods_type.goods = goods_list

            context = {'goods_types': goods_types}
            cache.set('index_data', context, 60 * 60 * 2)  # 设置缓存为2小时

        return render(request, 'goods/index.html', context)

    @staticmethod
    def index_rotation(request):
        """首页轮播图"""
        if request.method == "GET":
            rotations_list = cache.get('rotations_list')
            if not rotations_list:
                rotations = RotationCharts.objects.filter(is_rotate=True)[:4]
                rotations_list = [{'img': rotation.image.url, 'desc': rotation.name} for rotation in rotations]
                cache.set('rotations_list', rotations_list, 60 * 60 * 2)
            return JsonResponse({'data': rotations_list})


class GoodsDetailView(BaseGoodsView):
    def get(self, request, goods_sku_id):
        try:
            goods = GoodsSKU.objects.get(id=goods_sku_id)
        except GoodsSKU.DoesNotExist:
            return redirect(reverse('goods:index'))

        goods_types = self.get_navigation_info()  # 导航栏信息

        # 查询该商品的所有图片
        goods_dynamics = GoodsDynamics.objects.filter(goods_sku_id=goods_sku_id)
        goods_images = []
        for goods_dynamic in goods_dynamics:
            images = GoodsImage.objects.filter(goods_dynamics_id=goods_dynamic.id)
            for image in images:
                goods_images.append({'img': image.image.url})

        # 查询相同类型的热销商品
        hot_goods = self.query_hot_goods(goods)
        # 查询商品的大小和颜色
        specs_data, product_data = self.query_goods_dynamics(goods_dynamics)
        # 评分、满意度、评论
        score, satisfy, comments = self.get_goods_comments(goods_sku_id)

        context = {
            'goods_types': goods_types,
            'goods': goods,
            'goods_images': goods_images,
            'hot_goods': hot_goods,
            'specs_data': specs_data,
            'product_data': product_data,
            'score': score,
            'satisfy': satisfy,
            'comments': comments
        }
        return render(request, 'goods/detail.html', context)

    @staticmethod
    def get_goods_comments(goods_sku_id):
        from .models import GoodsComment
        comments = GoodsComment.objects.filter(goods_sku_id=goods_sku_id).order_by('-create_time')
        if not comments:
            return 0, 0, None
        # 总评分
        amount_score = sum(map(lambda x: x.score, comments))
        # 评分
        score = round(amount_score / len(comments), 2)
        # 满意度
        satisfy = (len(list(filter(lambda x: x.score >= 3, comments))) / len(comments)) * 100
        return score, round(satisfy, 2), comments

    @staticmethod
    def query_goods_dynamics(dynamics):
        """查询该商品的所有搭配"""
        specs_data = []
        product_data = []
        color_set = []  # 存放该商品的所有颜色
        size_set = []  # 存放该商品的所有大小/尺寸

        for dynamic in dynamics:
            if dynamic.size not in map(lambda x: x['name'], size_set):  # 为大小去重
                size_set.append({'id': dynamic.id, 'name': dynamic.size, 'spec': '大小'})
            if dynamic.color not in map(lambda x: x['name'], color_set):  # 为颜色去重
                color_set.append({'id': dynamic.id, 'name': dynamic.color, 'spec': '颜色'})

            product_data.append({
                'id': dynamic.id,
                'options': [
                    {'id': dynamic.id, 'name': dynamic.size, 'spec': '大小'},
                    {'id': dynamic.id, 'name': dynamic.color, 'spec': '颜色'}
                ],
                'spu': dynamic.goods_sku.goods_spu_id,
                'price': dynamic.price,
                'stock': dynamic.stock,
                'sales': dynamic.sales
            })

        specs_data.append({'id': dynamics[0].goods_sku_id, 'name': '大小', 'class_set': size_set})
        specs_data.append({'id': dynamics[0].goods_sku_id, 'name': '颜色', 'class_set': color_set})

        return specs_data, product_data

    @staticmethod
    def query_hot_goods(goods):
        """同类型热卖商品"""
        total_sku = GoodsSKU.objects.filter(goods_type_id=goods.goods_type.id)
        hot_goods = []
        for sku in total_sku:
            goods_dynamics = GoodsDynamics.objects.filter(goods_sku_id=sku.id)
            for goods_dynamic in goods_dynamics:
                if goods_dynamic.goods_sku_id != goods.id:  # 排除自身
                    if goods_dynamic.goods_sku_id not in map(lambda x: x.goods_sku_id, hot_goods):  # 排除相同sku商品
                        goods_dynamic.image = GoodsImage.objects.filter(goods_dynamics_id=goods_dynamic.id)[0].image.url
                        hot_goods.append(goods_dynamic)

        hot_goods = list(sorted(hot_goods, key=lambda x: x.sales, reverse=True))[:4]  # 按销量降序
        return hot_goods


class GoodsListView(BaseGoodsView):
    def get(self, request, show_type, page):
        goods_types = self.get_navigation_info()  # 导航栏信息
        for goods_type in goods_types:
            goods_type.is_active = True if goods_type.logo == show_type else False

        if show_type == 'all':
            goods_sku = GoodsSKU.objects.all()
        else:
            goods_type = GoodsType.objects.get(logo=show_type)
            goods_sku = GoodsSKU.objects.filter(goods_type_id=goods_type.id)

        total_goods = self.get_sku_image(goods_sku)

        try:
            items = list(request.GET.items())
            sort_key = items[0][1]  # 排序关键字
            total_goods = list(self.sort_goods(total_goods, sort_key))
        except IndexError:
            items = ''

        from utils.paginator.paginator import MyPaginator
        paginator = MyPaginator(total_goods, 8)
        pages = paginator.page(page)
        pages.my_page_range = paginator.show_part_page_range(page, num_pages=10)

        context = {
            'show_type': show_type,
            'goods_types': goods_types,
            'pages': pages,
            'sorted': '?'
        }
        if items:
            context['sorted'] = f'?{items[0][0]}={items[0][1]}'

        return render(request, 'goods/list.html', context)

    @staticmethod
    def sort_goods(total_goods, sort_key):
        sort_choice = {
            'price': sorted(total_goods, key=lambda x: x.price),
            '-price': sorted(total_goods, key=lambda x: x.price, reverse=True),
            'sales': sorted(total_goods, key=lambda x: x.sales),
            '-sales': sorted(total_goods, key=lambda x: x.sales, reverse=True),
            'date': sorted(total_goods, key=lambda x: x.create_time),
            '-date': sorted(total_goods, key=lambda x: x.create_time, reverse=True),
        }

        return sort_choice[sort_key]


class SearchView(BaseGoodsView):
    def get(self, request, page):
        goods_types = self.get_navigation_info()  # 导航栏信息
        content = request.GET.get('search')  # 搜索内容
        if not content:
            return redirect(reverse('goods:list', kwargs={'show_type': 'all', 'page': 1}))
        goods_sku = GoodsSKU.objects.filter(name__icontains=content)  # 模糊查询

        total_goods = self.get_sku_image(goods_sku)

        from utils.paginator.paginator import MyPaginator
        paginator = MyPaginator(total_goods, 4)
        pages = paginator.page(page)
        pages.my_page_range = paginator.show_part_page_range(page, num_pages=10)

        context = {
            'pages': pages,
            'show_type': 'all',
            'goods_types': goods_types
        }

        return render(request, 'goods/list.html', context)

templates/goods/detail.html
{% extends 'base_templates/base.html' %}

{% block title %}{{ goods.name }}{% endblock %}

{% block breadcrumb %}
    <div class="container">
        <nav class="breadcrumb is-marginless mt-3 mb-3 is-small" aria-label="breadcrumbs">
            <ul>
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li><a href="{% url 'goods:list' goods.goods_type.logo 1 %}">{{ goods.goods_type.name }}</a></li>
                <li class="is-active">{{ goods.name }}</li>
            </ul>
        </nav>
    </div>
{% endblock breadcrumb %}

{% block container %}
    <div class="columns">
        <div class="column is-3">
            <style>
                [v-cloak] {
                    display: none;
                }
                .is-active .al img {
                    filter: grayscale(0%);
                }
                .al img {
                    filter: grayscale(100%);
                }
            </style>
            <div id="banners">
                {{ goods_images|json_script }}
                <div id="banners-data"></div>
                <b-carousel :indicator-inside="false">
                    <b-carousel-item v-for="item in bannersDatas">
                        <b-image class="image" ratio="1by1" :src="getImgUrl(item.img)"></b-image>
                    </b-carousel-item>
                    <template #indicators="props">
                        <b-image class="al image" :src="getImgUrl(bannersDatas[props.i].img)"></b-image>
                    </template>
                </b-carousel>
            </div>
            <script>
                var banner_data_element = document.getElementById('banners-data');
                var bannersDatas = JSON.parse(banner_data_element.previousElementSibling.textContent);
                var banners = new Vue({
                    el: "#banners",
                    delimiters: ['{$', '$}'],
                    data: {
                        bannersDatas
                    },
                    methods: {
                        getImgUrl(value) {
                            return `${value}`
                        },
                    },
                })
            </script>
        </div>
        <div class="column">
            <h1 class="is-size-5 has-text-justified has-text-weight-bold mb-2">{{ goods.name }}</h1>
            <div id="product">
                {{ product_data|json_script }}
                <div id="product-data"></div>
                {{ specs_data|json_script }}
                <div id="specs-data"></div>
                <div class="box is-marginless is-radiusless has-background-primary-dark has-text-white-ter">
                    <div class="is-flex is-justify-content-space-between is-align-items-center">
                        <div>
                            <span class="is-size-7">价格：</span>
                            <h1 class="is-size-4">¥ {$ sku.price $}</h1>
                        </div>
                        <div class=" has-text-centered">
                            {$ sku.sales $}
                            <h1>销量</h1>
                        </div>
                    </div>
                </div>

                <!-- specs规格数据获取 -->
                <div class="box is-radiusless is-marginless">
                    <div class="is-flex is-align-items-center" v-for="spec, index in specsData" style="height:40px;">
                        <div class="has-text-grey-light">{$ spec.name $}：</div>
                        <div class="is-flex is-flex-wrap-wrap is-flex-grow-1">
                            <div class="mr-2" v-for="op, i in spec.class_set" :key="op.id"
                                 style="flex: 0 0 25%;">
                                <b-radio-button v-model="radioButton[index]"
                                                :native-value="op.name"
                                                size="is-small"
                                                type="is-primary is-light is-outlined">
                                    <span>{$ op.name $}</span>
                                </b-radio-button>
                            </div>
                        </div>
                    </div>

                    <!-- 数量 -->
                    <div class=" is-flex is-align-items-center mt-3">
                        <div class=" has-text-grey-light">数量：</div>
                        <div>
                            <b-numberinput
                                    controls-position="compact"
                                    min="1"
                                    :max="stock"
                                    v-model="num"
                                    size="is-small"
                                    :editable="false">
                            </b-numberinput>
                        </div>
                        <div class=" has-text-grey-dark ml-3">(库存{$ stock $})</div>
                    </div>
                    <!-- 数量end -->
                </div>

                <!-- 加入购物车按钮及一键购买 -->
                <div class="box is-radiusless">
                    <b-button
                        type="is-primary"
                        @click="addCart"
                        :disabled="stock ? false : true">
                        加入购物车
                    </b-button>
                    <b-button
                        type="is-primary"
                        :disabled="stock ? false : true"
                        @click="nowBuy"
                        outlined>
                        立即购买
                    </b-button>
                </div>
                <!-- 加入购物车按钮及一键购买 -->
                <div class="box is-radiusless mt-3">
                <b-tabs class="block">
                    <b-tab-item label="商品详情">
                        <div class="content">
                            {% for goods_image in goods_images %}
                                <p><img src="{{ goods_image.img }}" alt="{{ goods_image.img }}"></p>
                            {% endfor %}
                        </div>
                    </b-tab-item>
                    <b-tab-item label="商品评价">
                        {% if comments %}
                            <div class="is-flex is-justify-content-space-between p-2">
                                <div class="">满意度：{{ satisfy }}%</div>
                                <div class="is-flex is-align-items-center">
                                    <span> 评分：</span>
                                    <b-rate
                                        :value="{{ score }}"
                                        disabled
                                        custom-text="{{ score }}分">
                                    </b-rate>
                                </div>
                            </div>
                            <div class="dropdown-divider"></div>
                        {% endif %}
                        {% for comment in comments %}
                            <article class="media">
                                <figure class="media-left">
                                    <p class="image is-32x32">
                                        <img class="is-rounded" src="{{ comment.user.image.url }}" alt="图片异常">
                                    </p>
                                </figure>
                                <div class="media-content">
                                    <p>
                                        {{ comment.user.username }}
                                        <b-rate size="is-small" :value="{{ comment.score }}" disabled custom-text="{{ comment.score }}分"></b-rate>
                                    </p>
                                    <p class=" is-size-7">{{ comment.create_time }}</p>
                                    <p class=" has-text-grey-light">{{ comment.content }}</p>
                                </div>
                            </article>
                        {% empty %}
                            <p class=" has-text-centered has-text-danger mt-6">还没有任何评价内容哦！</p>
                        {% endfor %}
                    </b-tab-item>
                </b-tabs>
            </div>
                <!-- 详情 -->
            </div>
        </div>
        <div class="column is-2">
            <h1 class="has-text-centered has-background-white pt-3 is-size-6 pb-3 has-text-weight-bold">热销排行</h1>
            <div class=" dropdown-divider is-marginless"></div>
            {% for hot in hot_goods %}
                <div class="has-background-white">
                    <figure class="image is-1by1">
                        <a href="{% url 'goods:detail' hot.goods_sku.id %}"><img src="{{ hot.image }}"
                                                                                 alt="{{ hot.goods_sku.name }}"></a>
                    </figure>
                    <div class="is-flex-grow-1 is-flex is-flex-direction-column is-justify-content-center">
                        <p class="has-text-justified spu-title pl-3 pr-3">
                            <a href="{% url 'goods:detail' hot.goods_sku.id %}"
                               class="has-text-black-ter">{{ hot.goods_sku.name }}</a>
                        </p>
                    </div>
                    <div class="pl-2 pr-2 pb-2">
                        <div class="is-flex is-align-items-center is-justify-content-space-between">
                            <span class="is-size-5 has-text-danger-dark">¥{{ hot.price }}</span>
{#                            <span class="tag is-danger is-light is-size-7">券</span>#}
                        </div>
                        <div class="is-flex is-align-items-center is-justify-content-space-between">
                            <span class="is-size-7 has-text-grey-light">{{ hot.sales }}人付款</span>
                        </div>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
            {% endfor %}
        </div>
    </div>
{% endblock %}


{% block vue %}
    <script>
        var product_element = document.getElementById('product-data');
        var specs_element = document.getElementById('specs-data');

        var specsData = JSON.parse(specs_element.previousElementSibling.textContent);
        var productData = JSON.parse(product_element.previousElementSibling.textContent);

        var product = new Vue({
            el: "#product",
            delimiters: ['{$', '$}'],
            data: {
                productData,
                specsData,
                sku: {
                    price: 0,
                    cost_price: 0,
                    sales: 0,
                    stock: 0,
                },
                num: 1,
                stock: 0,
                radioButton: [],
                watchProductDatas: {}
            },
            created() {
                this.getProduct()
            },
            methods: {
                getProduct() {
                    if (this.productData.length > 0) {
                        this.watchProduct()
                        let sku_item = this.productData[0]
                        let ops = this.getOpsName(sku_item.options)
                        // 默认选中规格
                        this.sku = this.watchProductDatas[ops]
                        this.radioButton = ops.split(',')
                    }
                },

                // 整理数据
                watchProduct() {
                    this.productData.forEach(element => {
                        let ops = this.getOpsName(element.options)
                        this.watchProductDatas[ops] = element
                    });
                },

                // 获取sku规格
                getOpsName(ops) {
                    let ops_items = []
                    ops.forEach(op => {
                        ops_items.push(op.name)
                    })
                    return ops_items.join()
                },

                // 加入购物车
                addCart() {
                    request({
                        url: "{% url 'cart:add' %}",
                        method: 'post',
                        data: {
                            dynamics: this.sku.id,
                            count: this.num
                        }
                    }).then(res => {
                        if (res.data.status === 200) {
                            bayke.toastMessage('is-success', '加入购物车成功');
                            var cart_element = document.getElementById('cart_dynamic');
                            cart_element.innerText = '购物车' + '（' + String(res.data.cart_len) + '）'
                        }
                        else {
                            bayke.toastMessage("is-danger", res.data.errmsg);
                        }
                    })
                },

                // 立即购买
                nowBuy() {
                    location.href = '{% url "order:buy" %}?dynamics_id='+`${this.sku.id}&count=${this.num}`
                }
            },
            watch: {
                // 监听点击规格
                radioButton: {
                    handler: function (val) {
                        let specs = val.join()
                        let item_sku = this.watchProductDatas[specs]
                        if (item_sku) {
                            this.sku = item_sku
                            this.stock = item_sku.stock
                        } else {
                            this.stock = 0
                        }
                    },
                    immediate: true,
                    deep: true
                }
            }
        })
    </script>
{% endblock %}
    

templates/goods/index.html
{% extends 'base_templates/base.html' %}

{% load static %}

{% block title %}家电之选-首页{% endblock %}

{% block banners %}
    <div class="has-background-white">
        {% include 'base_templates/banners.html' %}
    </div>
{% endblock %}

{% block container %}
    <div class="container mt-4 mb-4">
        {% for goods_type in goods_types %}
            <div class="is-flex is-align-items-center is-justify-content-space-between mb-2">
                <div class="">
                    <h1 class=" has-text-weight-semibold is-size-5">{{ goods_type.name }}</h1>
                </div>
                <div class="">
                    <a href="{% url 'goods:list' goods_type.logo 1 %}">更多>></a>
                </div>
            </div>
            <div class="columns is-multiline is-mobile">
                <div class="column is-4-fullhd is-6-tablet is-12-mobile">
                    <figure class="image is-4by3">
                        <img src="{{ goods_type.image.url }}" alt="{{ goods_type.name }}" srcset="">
                    </figure>
                </div>
                {% for goods in goods_type.goods %}
                    <div class="column is-2-fullhd is-3-tablet is-6-mobile">
                        <div class="is-flex is-flex-direction-column is-justify-content-space-between has-background-white"
                             style="height:100%">
                            <figure class="image is-1by1">
                                <a href="{% url 'goods:detail' goods.goods_sku.id %}"><img src="{{ goods.image }}" alt="{{ goods.goods_sku.name}}"></a>
                            </figure>
                            <div class="is-flex-grow-1 is-flex is-flex-direction-column is-justify-content-center">
                                <p class="has-text-justified spu-title pl-3 pr-3">
                                    <a href="{% url 'goods:detail' goods.goods_sku.id %}" class="has-text-black-ter">{{ goods.goods_sku.name }}</a>
                                </p>
                            </div>
                            <div class="pl-2 pr-2 pb-2">
                                <div class="is-flex is-align-items-center is-justify-content-space-between">
                                    <span class="is-size-5 has-text-danger-dark">¥{{ goods.price }}</span>
                                </div>
                                <div class="is-flex is-align-items-center is-justify-content-space-between">
                                    <span class="is-size-7 has-text-grey-light">{{ goods.sales }}人付款</span>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock %}