HomeAppliances/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('', include('apps.goods.urls', namespace='goods')),
    path('user/', include('apps.user.urls', namespace='user')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path("admin/", admin.site.urls),
]

apps/goods/urls.py
from django.urls import path
from .views import *

app_name = 'goods'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # 首页
    path('rotation', IndexView.index_rotation, name='rotation'),  # 首页轮播图
    path('goods/detail/<int:goods_sku_id>', GoodsDetailView.as_view(), name='detail'),  # 商品详情页
    path('goods/list/<str:show_type>/<int:page>', GoodsListView.as_view(), name='list'),  # 商品列表页
    path('goods/search/all/<int:page>', SearchView.as_view(), name='search'),  # 搜索页面
]

apps/order/urls.py
from django.urls import path
from .views import *


app_name = 'order'
urlpatterns = [
    path('order', OrderView.as_view(), name='order'),  # 订单页面（显示订单、提交订单）
    path('buy', NowBuyView.as_view(), name='buy'),  # 立即购买商品
    path('pay/<str:order_id>', PayView.as_view(), name='pay'),  # 支付页面
    path('pay/status/check', AliPayView.as_view(), name='check'),  # 支付结果查询
    path('payok/<str:order_id>', PayOkView.as_view(), name='payok'),  # 支付成功页面
    path('confirm', ConfirmReceiptView.as_view(), name='confirm'),  # 确认收货
    path('comment/<str:order_id>', GoodsCommentView.as_view(), name='comment')  # 订单评价
]

apps/user/urls.py
from django.urls import path
from .views import *

app_name = 'user'
urlpatterns = [
    path('', UserCenterView.as_view(), name='user'),  # 用户中心页
    path("login/", LoginView.as_view(), name='login'),  # 登录
    path("register", RegisterView.as_view(), name='register'),  # 注册
    path('send', SendCode.as_view(), name='send'),  # 发送注册码
    path('logout', LogoutView.as_view(), name='logout'),  # 退出登录
    path('banlance', BalanceView.as_view(), name='balance'),  # 用户余额
    path('address', AddressView.as_view(), name='address'),  # 用户地址
    path('modify_address', ModifyAddressView.as_view(), name='modify_address'),  # 改变地址
    path('my_order/<int:page>', UserOrderView.as_view(), name='my_order'),  # 我的订单
    path('order_detail/<str:order_id>', OrderDetailView.as_view(), name='order_detail'),  # 订单详情
    path('recharge', RechargeView.as_view(), name='recharge'),  # 充值
    path('upload_image', ModifyImageView.as_view(), name='image')  # 更换头像
]

apps/order/models.py
from django.db import models
from db.base_model import BaseModel
from ..user.models import MyUser, Address


class OrderInfo(BaseModel):
    ORDER_STATUS_CHOICES = (
        (1, '待支付'),
        (2, '待发货'),
        (3, '待收货'),
        (4, '待评价'),
        (5, '已完成')
    )

    ORDER_STATUS_DICT = {
        1: '待支付',
        2: '待发货',
        3: '待收货',
        4: '待评价',
        5: '已完成'
    }

    PAY_METHODS_CHOICES = (
        (1, '货到付款'),
        (2, '微信支付'),
        (3, '支付宝'),
        (4, '余额支付')
    )

    PAY_METHODS_DICT = {
        1: '货到付款',
        2: '微信支付',
        3: '支付宝',
        4: '余额支付'
    }

    PAY_METHODS_ICONS = {
        1: '/media/img/hdpay.svg',
        2: '/media/img/wxpay.svg',
        3: '/media/img/alipay.svg',
        4: '/media/img/ye.svg'
    }

    order_id = models.CharField('订单id', primary_key=True, max_length=40)
    total_price = models.DecimalField('订单总价', max_digits=11, decimal_places=2)
    freight = models.DecimalField('运费', max_digits=11, decimal_places=2)
    total_count = models.IntegerField('商品总数', null=False)
    pay_method = models.SmallIntegerField('支付方式', default=3, choices=PAY_METHODS_CHOICES)
    status = models.SmallIntegerField('订单状态', choices=ORDER_STATUS_CHOICES, default=1)
    trade_no = models.CharField('订单编号', max_length=40, null=False)
    mark = models.CharField('订单留言', max_length=255, default='')
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, verbose_name='所属用户')
    address = models.ForeignKey(Address, on_delete=models.CASCADE, verbose_name='订单地址')

    class Meta:
        verbose_name = '订单信息表'
        verbose_name_plural = verbose_name
        db_table = 'order_info'

    def __str__(self):
        return self.order_id


class GoodsOrder(BaseModel):
    from ..goods.models import GoodsDynamics
    price = models.DecimalField('商品总价', max_digits=11, decimal_places=2, null=False)
    count = models.IntegerField('商品总数', null=False)
    is_commented = models.BooleanField('是否评价', default=False)
    goods_dynamics = models.ForeignKey(GoodsDynamics, on_delete=models.CASCADE, verbose_name='商品动态')
    order_info = models.ForeignKey(OrderInfo, on_delete=models.CASCADE, verbose_name='订单信息')

    class Meta:
        verbose_name = '商品订单表'
        verbose_name_plural = verbose_name
        db_table = 'goods_order'

    def __str__(self):
        return self.goods_dynamics.goods_sku.name

apps/order/views.py
from django.shortcuts import render, redirect, reverse
from ..goods.views import BaseGoodsView
from ..goods.models import GoodsDynamics, GoodsImage, GoodsComment
from ..user.models import Address, MyUser
from .models import GoodsOrder, OrderInfo
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.conf import settings
from alipay import AliPay  # pip install python-alipay-sdk
from django.db import transaction
from django_redis import get_redis_connection
from json import loads


class OrderView(LoginRequiredMixin, BaseGoodsView):
    def get(self, request):
        dynamics_ids = request.GET.get('dynamics').split(',')

        dynamics = []
        total_count = 0
        amount_price = 0
        freight = 10
        cart_id = f'cart_{request.user.id}'
        connect = get_redis_connection()

        for dynamics_id in dynamics_ids:
            options = []
            dynamic = GoodsDynamics.objects.get(id=dynamics_id)  # 商品动态
            image = GoodsImage.objects.filter(goods_dynamics_id=dynamics_id)[0]  # 商品的一张图片
            count = int(connect.hget(cart_id, dynamics_id))  # 通过购物车查询该商品的总数
            options.append({'spec': '大小', 'name': dynamic.size})
            options.append({'spec': '颜色', 'name': dynamic.color})

            dynamics.append({
                'name': dynamic.goods_sku.name,
                'id': dynamics_id,
                'image': image.image.url,
                'price': float(dynamic.price),
                'options': options,
                'count': count,
                'total_price': count * float(dynamic.price)
            })

            total_count += count
            amount_price += float(dynamic.price) * count

        context = {
            'goods_types': self.get_navigation_info(),  # 导航栏信息
            'dynamics': dynamics,
            'total_count': total_count,  # 商品总数
            'amount_price': amount_price,  # 商品总价（不包含运费）
            'total_price': amount_price + freight,  # 商品总价（包含运费）
            'freight': freight  # 运费
        }

        return render(request, 'order/order_list.html', context)

    @transaction.atomic  # 绑定事务
    def post(self, request):
        form_data = eval(request.body)
        dynamics_datas = form_data.get('dynamics_datas')
        amount_price = form_data.get('amount_price')
        total_count = form_data.get('total_count')
        address_id = form_data.get('addr_id')
        mark = form_data.get('mark')

        response = {
            'success': 0,
            'status': -1,
        }

        if not all([*dynamics_datas, amount_price, total_count, address_id]):
            response['errmsg'] = '请填写完整数据'
            return JsonResponse(response)

        try:
            Address.objects.get(id=address_id)
        except Address.DoesNotExist:
            response['errmsg'] = '该地址不存在'
            return JsonResponse(response)

        # 核心业务处理
        from time import time
        from datetime import datetime
        order_id = str(int(time())) + str(request.user.id)  # 订单编号
        trade_no = datetime.now().strftime('%Y%m%d%H%M%S') + str(request.user.id)  # 交易编号
        save_id = transaction.savepoint()  # 事务保存点
        try:
            order_info = OrderInfo.objects.create(
                order_id=order_id,
                total_price=amount_price,
                address_id=address_id,
                freight=10,
                user=request.user,
                mark=mark,
                total_count=total_count,
                trade_no=trade_no
            )
            connect = get_redis_connection()
            for dynamics_data in dynamics_datas:
                dynamics_id = dynamics_data.get('id')
                count = dynamics_data.get('count')

                try:
                    dynamic = GoodsDynamics.objects.select_for_update().get(id=dynamics_id)  # 悲观锁
                except GoodsDynamics.DoesNotExist:
                    transaction.savepoint_rollback(save_id)  # 回滚到事务保存点
                    response['errmsg'] = f'id为{dynamics_id}的商品不存在'
                    return JsonResponse(response)

                if dynamic.stock < count:
                    transaction.savepoint_rollback(save_id)  # 回滚到事务保存点
                    response['errmsg'] = f'{dynamic.goods_sku.name}库存不足'
                    return JsonResponse(response)

                GoodsOrder.objects.create(
                    count=count,
                    price=count*dynamic.price,
                    goods_dynamics_id=dynamics_id,
                    order_info=order_info
                )
                dynamic.sales += count
                dynamic.stock -= count
                dynamic.save()

        except Exception as exception:
            transaction.savepoint_rollback(save_id)  # 回滚到事务保存点
            response['errmsg'] = '订单异常，请重试'
            response['exception'] = exception
            return JsonResponse(response)

        transaction.savepoint_commit(save_id)  # 提交事务
        # 倒计时完毕后用户未支付则删除订单
        from celery_tasks.tasks import check_order_is_pay_task, get_delay_time
        eta = get_delay_time(hours=24)
        check_order_is_pay_task.apply_async(args=(order_id,), eta=eta)

        dynamics_ids = list(map(lambda x: x['id'], dynamics_datas))  # 获取所有商品动态id
        connect.hdel(f'cart_{request.user.id}', *dynamics_ids)  # 清除购物车数据

        response['success'] = 1
        response['status'] = 200
        response['order_id'] = order_id

        return JsonResponse(response)


class NowBuyView(LoginRequiredMixin, BaseGoodsView):
    def get(self, request):
        dynamics_id = request.GET.get('dynamics_id')
        count = int(request.GET.get('count', 1))
        dynamic = GoodsDynamics.objects.get(id=dynamics_id)
        image = GoodsImage.objects.filter(goods_dynamics_id=dynamics_id)[0]

        dynamics = [{
            'name': dynamic.goods_sku.name,
            'id': dynamics_id,
            'image': image.image.url,
            'price': float(dynamic.price),
            'count': count,
            'options': [
                {'spec': '大小', 'name': dynamic.size},
                {'spec': '颜色', 'name': dynamic.color}
            ],
            'total_price': count * float(dynamic.price)
        }]

        context = {
            'goods_types': self.get_navigation_info(),
            'dynamics': dynamics,
            'total_count': count,
            'amount_price': count * float(dynamic.price),
            'total_price': count * float(dynamic.price) + 10,
            'freight': 10,
        }

        return render(request, 'order/order_list.html', context)


class AliPayView(BaseGoodsView):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # 读取app私钥
        with open('apps/order/app_private_key.pem', 'r', encoding='utf-8') as f1:
            app_private_key_string = f1.read()

        # 读取支付宝公钥
        with open('apps/order/alipay_public_key.pem', 'r', encoding='utf-8') as f2:
            alipay_public_key_string = f2.read()

        self.alipay = AliPay(
            appid=settings.ALIPAY_APP_ID,
            app_private_key_string=app_private_key_string,
            alipay_public_key_string=alipay_public_key_string,
            debug=True  # 为True的时候调用沙箱接口，反之调用真实的支付接口
        )

    @classmethod
    def get_return_url(cls, order_id):
        if settings.DEBUG:
            return None
        return ''.join(['http', '://', settings.HOST_NAME, f'/order/payok/{order_id}'])

    def get_alipay_url(self, order):
        """获取支付宝支付链接"""
        params = self.alipay.api_alipay_trade_page_pay(
            out_trade_no=order.trade_no,
            total_amount=float(order.total_price + order.freight),
            subject='家电之选-订单支付',
            return_url=self.get_return_url(order.order_id),  # 用户支付后返回的页面URL
            notify_url=None  # 支付结果通知的URL
        )

        payment_url = settings.ALIPAY_GATEWAY_URL + params

        response = {
            'status': 200,
            'payment_url': payment_url,
            'success': 1,
            'pay_method': 3
        }

        return JsonResponse(response)

    def post(self, request):
        """校验支付结果（仅在开发环境中使用）"""
        if not request.user.is_authenticated:
            return JsonResponse({'status': -1, 'success': 0, 'errmsg': '用户未登录'})
        from time import sleep
        trade_no = eval(request.body).get('trade_no')
        # 进入支付监听状态
        try:
            while True:
                try:
                    response = self.alipay.api_alipay_trade_query(trade_no)  # 查询支付状态
                except Exception as e:
                    return JsonResponse({'status': -1, 'errmsg': f'支付异常{e}', 'success': 0})
                code = response.get('code')  # 支付状态码
                trade_status = response.get('trade_status')  # 交易状态

                if code == '40004' or (code == '10000' and trade_status == 'WAIT_BUYER_PAY'):  # 等待支付中……
                    print('等待支付中……')
                    sleep(5)
                elif code == '10000' and trade_status == 'TRADE_SUCCESS':  # 支付成功
                    try:
                        order = OrderInfo.objects.get(trade_no=trade_no)
                    except OrderInfo.DoesNotExist:
                        return JsonResponse({'status': -1, 'success': 0, 'msg': '非法请求'})
                    user = MyUser.objects.get(id=request.user.id)

                    order.pay_method = 3
                    order.status = 2
                    user.total_consumption += (order.total_price + order.freight)

                    user.save()
                    order.save()
                    return JsonResponse({'status': 200, 'success': 1, 'msg': '订单支付成功'})
                else:
                    return JsonResponse({'status': -1, 'success': 0, 'errmsg': '支付失败'})
        except TimeoutError:
            self.alipay.api_alipay_trade_close(trade_no)  # 主动关闭交易
            return JsonResponse({'status': -1, 'success': 0, 'errmsg': '支付时间过长，支付失败'})

templates/order/order_list.html
{% extends 'base_templates/base.html' %}

{% load i18n static %}

{% block title %}订单确认{% endblock %}

{% block breadcrumb %}
<div class="container">
	<nav class="breadcrumb is-marginless mt-3 mb-3 is-small" aria-label="breadcrumbs">
		<ul>
			<li><a href="{% url 'goods:index' %}">首页</a></li>
			<li class="is-active">&emsp;订单确认</li>
		</ul>
	</nav>
</div>
{% endblock %}

{% block container %}

<div class="box">
	<h1 class="is-size-5">收货地址</h1>
	<img width="100%" src="{% url 'media' 'img/line.png' %}" alt="line">
	{% include 'base_templates/base_address.html' with update=True delete=False %}
</div>

<div class="box">
	<h1 class="is-size-5">订单商品</h1>
	<div class=" dropdown-divider"></div>
	{% for dynamic in dynamics %}
		<div class="columns">
            <div class="column is-2 is-flex is-justify-content-center">
                <figure class="image is-128x128">
                    <img src="{{ dynamic.image }}" alt="{{ dynamic.name }}">
                </figure>
            </div>
            <div class="column is-flex is-flex-direction-column is-justify-content-center">
                <h1 class=" has-text-weight-bold">{{ dynamic.name }}</h1>
                <div class="has-text-grey-light">
                    {% for option in dynamic.options %}
                    <span class="mr-3">{{ option.spec }}：{{ option.name }}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="column is-2 is-flex is-justify-content-center is-align-items-center">
                {{ dynamic.price }}&ensp;x&ensp;{{ dynamic.count }}
            </div>
            <div class="column is-2 is-flex is-justify-content-center is-align-items-center">
                ¥{{ dynamic.total_price }}
            </div>
        </div>
	{% endfor %}

	<div class="dropdown-divider"></div>

	<div id="order">
		<div class="box is-shadowless is-radiusless has-background-light">
			<div class="field">
				<label class="label">订单留言</label>
				<div class="control">
					<textarea class="textarea" v-model="mark" name="mark" placeholder="请备注说明您的特殊要求..."></textarea>
				</div>
			</div>
		</div>

		<div class="is-flex is-flex-direction-column">
			<div class="is-flex mb-2">
				<div class="has-text-right" style="width:85%">{{ total_count }} 件商品，总商品金额：</div>
				<div class="has-text-left" style="width:10%; margin-left:5%;">¥{{ amount_price }} </div>
			</div>
			<div class="is-flex mb-2">
				<div class="has-text-right" style="width:85%">运费：</div>
				<div class="has-text-left" style="width:10%;margin-left:5%;">¥{{ freight }} </div>
			</div>
			<div class="is-flex has-text-danger-dark">
				<div class=" has-text-right is-size-5" style="width:85%">应付总额：</div>
				<div class=" has-text-left is-size-5" style="width:10%; margin-left:5%;">¥{{ total_price }} </div>
			</div>
		</div>
		<div class=" dropdown-divider"></div>
		<div class="has-text-right">
			<button class="button is-primary mt-2 pl-6 pr-6 is-large" @click="confirmOrder">提交订单</button>
		</div>

	</div>
</div>
{{ dynamics|json_script:"dynamics-data" }}
{% endblock %}

{% block vue %}
<script>
	var skusData = JSON.parse(document.getElementById('dynamics-data').textContent);
	var order = new Vue({
		el: "#order",
		delimiters: ['{$', '$}'],
		data: {
			mark: "",
			skus: skusData
		},
		methods: {
			getBaykeorderSKUSet(){
				let baykeordersku_set = []
				this.skus.forEach(element => {
					let item_skus = {}
					item_skus['id'] = element.id
					item_skus['count'] = element.count
					baykeordersku_set.push(item_skus)
				});
				return baykeordersku_set
			},

			confirmOrder() {
				let addr = address._data.formProps
				console.log(this.getBaykeorderSKUSet())
				request({
                    url: '{% url "order:order" %}',
					method: 'post',
					data: {
						dynamics_datas: this.getBaykeorderSKUSet(),
                        addr_id: addr.id,
                        amount_price: {{ amount_price }},
                        total_count: {{ total_count }},
                        mark: this.mark
					}
				}).then(res => {
					if (res.data.status == 200) {
                        var order_id = res.data.order_id
						location.href = "/order/pay/" + `${order_id}`
					} 
                    else {
						bayke.toastMessage('is-danger', res.data.errmsg);
                        if(res.data.exception) {
                            console.log(res.data.exception)
                        }
					}
				})

			}
		},
	})
</script>
{% endblock %}

templates/order/pay.html
{% extends 'base_templates/base.html' %}

{% load i18n static %}

{% block title %}收银台{% endblock %}

{% block breadcrumb %}
    <div class="container">
        <nav class="breadcrumb is-marginless mt-3 mb-3 is-small" aria-label="breadcrumbs">
            <ul>
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="is-active">&emsp;订单支付</li>
            </ul>
        </nav>
    </div>
{% endblock %}

{% block container %}
    <div class="box is-marginless is-radiusless has-background-primary-dark has-text-white-bis">
        <h1 class="is-size-3">订单提交成功！订单将在24小时后过期，记得及时付款哟~</h1>
    </div>
    <div class="box is-radiusless" style="line-height: 30px;">
        <p>订单编号：{{ trade_no }}</p>
        <p>订单总额：{{ total_amount }}元</p>
        <p>收货信息：{{ address }}</p>
    </div>

    <div class="box is-radiusless">
        <h1 class=" is-size-4">订单商品</h1>
        <div class="dropdown-divider"></div>
        {% for goods_order in goods_orders %}
            <div class="columns">
                <div class="column is-2 is-flex is-justify-content-center">
                    <figure class="image is-128x128">
                        <img src="{{ goods_order.image }}" alt="{{ goods_order.name }}">
                    </figure>
                </div>
                <div class="column is-flex is-flex-direction-column is-justify-content-center">
                    <h1 class=" has-text-weight-bold">{{ goods_order.name }}</h1>
                    <div class="has-text-grey-light">
                        {% for option in goods_order.options %}
                            <span class="mr-3">{{ option.spec }}：{{ option.name }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="column is-2 is-flex is-justify-content-center is-align-items-center">
                    {{ goods_order.goods_dynamics.price }}x{{ goods_order.count }}
                </div>
            </div>
            <div class="dropdown-divider"></div>
        {% endfor %}
    </div>

    <div class="box is-radiusless">
        <h1 class=" is-size-4">支付方式</h1>
        <div class="dropdown-divider"></div>
        {% include 'base_templates/paymethods.html' %}
        <div class="dropdown-divider"></div>
        <div class="has-text-right" id="nowPay">
            <button class="button is-danger is-large pl-6 pr-6" @click="savePay">立即支付</button>
        </div>
    </div>
{% endblock %}

{% block vue %}
    <script>
        var nowPay = new Vue({
            el: '#nowPay',
            delimiters: ['{$', '$}'],
            data: {},
            methods: {
                savePay() {
                    request({
                        url: "{% url 'order:pay' order_id %}",
                        method: 'post',
                        data: {
                            method: payMethod._data.defaultPay.value
                        }
                    }).then(res => {
                        // 捕获错误信息
                        if (!res.data.success) {
                            bayke.toastMessage('is-danger', res.data.errmsg);
                            return
                        }
                        if (res.data.pay_method === 3) {
                            bayke.toastMessage('is-success', '正在跳转到支付宝...')
                            setTimeout(() => {
                                window.open(res.data.payment_url)  // 开发环境
                                // location.href = res.data.payment_url  // 生产环境
                            }, 2000);
                            this.check_alipay_status()  // 开发环境使用，生产环境需要将其注释
                        } else if (res.data.pay_method === 4) {
                            this.pay_success()
                        }
                    })
                },
                pay_success() {
                    bayke.toastMessage('is-success', '订单支付成功，正在跳转...')
                    setTimeout(() => {
                        location.href = "{% url 'order:payok' order_id %}"
                    }, 2000);
                },
                // 开发环境中监听支付宝支付状态
                check_alipay_status() {
                    const url = '{% url 'order:check' %}';
                    fetch(url, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': getCookie('csrftoken'),
                        },
                        body: JSON.stringify({
                            trade_no: {{ trade_no }}
                        })
                    }).then(response => {
                        if (!response.ok) {
                            throw new Error('Network response was not ok');
                        }
                        return response.json();
                    }).then(data => {
                        // 处理响应数据
                        if (data.success) {
                            this.pay_success()
                        } else {
                            bayke.toastMessage('is-danger', data.errmsg);
                        }
                    })
                }
            },
        })
    </script>
{% endblock %}
    

templates/order/payok.html
{% extends 'base_templates/base.html' %}

{% block title %}
    支付成功
{% endblock title %}

{% block breadcrumb %}
<div class="container">
	<nav class="breadcrumb is-marginless mt-3 mb-3 is-small" aria-label="breadcrumbs">
		<ul>
			<li><a href="{% url 'goods:index' %}">首页</a></li>
			<li class="is-active">&emsp;支付成功</li>
		</ul>
	</nav>
</div>
{% endblock %}

{% block container %}
<div class="box is-radiusless is-marginless pl-6 pr-6" style="line-height: 30px;">
    <div class="is-flex is-flex-direction-column is-align-items-center mb-4">
        <figure class="image is-128x128">
        <img src="{% url 'media' 'img/payok.svg' %}" alt="支付成功">
        </figure>
        <h1 class=" is-size-3 ">支付成功</h1> 
    </div>
    <div class=" dropdown-divider"></div>
    <p>交易编号：{{ order.trade_no }}</p>
    <p>实际支付：{{ total_amount }}元</p>
    <p>收货信息：{{ address.province }}{{ address.city }}{{ address.country }}{{ address.detail_address }}（{{ address.recipient }}）收</p>
    <p>订单状态：{{ pay_status }}</p>
    <p>支付方式：{{ pay_method }}</p>
    <p>支付时间：{{ order.update_time }}</p>
    <div class=" dropdown-divider"></div>
    {% for goods_order in goods_orders %}
    <div class="columns">
        <div class="column is-2 is-flex is-justify-content-center">
            <figure class="image is-128x128">
                <img src="{{ goods_order.image }}" alt="{{ goods_order.name }}">
            </figure>
        </div>
        <div class="column is-flex is-flex-direction-column is-justify-content-center">
            <h1 class=" has-text-weight-bold">{{ goods_order.name }}</h1>
            <div class="has-text-grey-light">
                {% for option in goods_order.options %}
                <span class="mr-3">{{ option.spec }}：{{ option.name }}</span>
                {% endfor %}
            </div>
        </div>
        <div class="column is-2 is-flex is-justify-content-center is-align-items-center">
            {{ goods_order.goods_dynamics.price }}x{{ goods_order.count }}
        </div>
    </div>
    {% endfor %}
</div>

<div class="box is-radiusless">
    <div class=" buttons is-justify-content-center">
    <a class=" button is-success" href="{% url 'user:my_order' 1 %}?sort=0">查看订单</a>
    <a class=" button is-black" href="{% url 'goods:index' %}">返回首页</a>
    </div>
</div>
{% endblock %}