HomeAppliances/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('', include('apps.goods.urls', namespace='goods')),
    path('user/', include('apps.user.urls', namespace='user')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path("admin/", admin.site.urls),
]

apps/goods/urls.py
from django.urls import path
from .views import *

app_name = 'goods'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # 首页
    path('rotation', IndexView.index_rotation, name='rotation'),  # 首页轮播图
    path('goods/detail/<int:goods_sku_id>', GoodsDetailView.as_view(), name='detail'),  # 商品详情页
    path('goods/list/<str:show_type>/<int:page>', GoodsListView.as_view(), name='list'),  # 商品列表页
    path('goods/search/all/<int:page>', SearchView.as_view(), name='search'),  # 搜索页面
]

apps/order/urls.py
from django.urls import path
from .views import *


app_name = 'order'
urlpatterns = [
    path('order', OrderView.as_view(), name='order'),  # 订单页面（显示订单、提交订单）
    path('buy', NowBuyView.as_view(), name='buy'),  # 立即购买商品
    path('pay/<str:order_id>', PayView.as_view(), name='pay'),  # 支付页面
    path('pay/status/check', AliPayView.as_view(), name='check'),  # 支付结果查询
    path('payok/<str:order_id>', PayOkView.as_view(), name='payok'),  # 支付成功页面
    path('confirm', ConfirmReceiptView.as_view(), name='confirm'),  # 确认收货
    path('comment/<str:order_id>', GoodsCommentView.as_view(), name='comment')  # 订单评价
]

apps/user/urls.py
from django.urls import path
from .views import *

app_name = 'user'
urlpatterns = [
    path('', UserCenterView.as_view(), name='user'),  # 用户中心页
    path("login/", LoginView.as_view(), name='login'),  # 登录
    path("register", RegisterView.as_view(), name='register'),  # 注册
    path('send', SendCode.as_view(), name='send'),  # 发送注册码
    path('logout', LogoutView.as_view(), name='logout'),  # 退出登录
    path('banlance', BalanceView.as_view(), name='balance'),  # 用户余额
    path('address', AddressView.as_view(), name='address'),  # 用户地址
    path('modify_address', ModifyAddressView.as_view(), name='modify_address'),  # 改变地址
    path('my_order/<int:page>', UserOrderView.as_view(), name='my_order'),  # 我的订单
    path('order_detail/<str:order_id>', OrderDetailView.as_view(), name='order_detail'),  # 订单详情
    path('recharge', RechargeView.as_view(), name='recharge'),  # 充值
    path('upload_image', ModifyImageView.as_view(), name='image')  # 更换头像
]

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel


# 拓展Django自带的用户模型类
class MyUser(AbstractUser, BaseModel):
    phone = models.CharField('手机号', max_length=11, null=True)
    introduce = models.TextField('个人介绍', default='', null=True)
    balance = models.DecimalField('余额', max_digits=11, decimal_places=2, default=0)  # 9位整数，2位小数
    total_recharge = models.DecimalField('累计充值', max_digits=11, decimal_places=2, default=0)
    total_consumption = models.DecimalField('累计消费', max_digits=11, decimal_places=2, default=0)
    image = models.ImageField('用户头像', upload_to='user', default='user/default.jpg')

    class Meta:
        verbose_name = '用户表'
        verbose_name_plural = verbose_name
        db_table = 'user_table'

    def __str__(self):
        return self.username


# 获取用户默认地址
class AddressManager:
    @staticmethod
    def get_user_default_address(user_id):
        try:
            address = Address.objects.filter(user_id=user_id).get(is_default=True)
        except Address.DoesNotExist:
            address = None

        return address


# 用户地址表
class Address(BaseModel):
    recipient = models.CharField('收件人', max_length=12)
    phone = models.CharField('手机号', max_length=11)
    province = models.CharField('省份', max_length=15)
    city = models.CharField('城市', max_length=10)
    country = models.CharField('区/县', max_length=10)
    detail_address = models.CharField('详细地址', max_length=40)
    is_default = models.BooleanField('默认地址', default=False)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, verbose_name='所属用户')
    manager = AddressManager()

    class Meta:
        verbose_name = '地址表'
        verbose_name_plural = verbose_name
        db_table = 'address_table'

    def __str__(self):
        return self.user.username

apps/user/forms.py
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.utils.translation import gettext_lazy
from django import forms


class LoginForm(AuthenticationForm):
    """ 登录表单 """
    username = UsernameField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            "class": "input",
            "placeholder": " 请输入用户名...",
            'value': 'rainbow'
        }))
    password = forms.CharField(
        label=gettext_lazy("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password",
            "class": "input",
            "placeholder": " 请输入密码...",
            'value': 'rainbow'
        }),
    )

apps/user/views.py
from re import match
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.contrib.auth import login, logout
from django.http import JsonResponse
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate
from .forms import LoginForm
from .models import MyUser, Address
from ..order.views import PayView


class SendCode(View):
    @staticmethod
    def post(request):
        form_info = eval(request.body.decode('utf-8'))
        username = form_info.get('username')
        email = form_info.get('email')
        password = form_info.get('password')

        response = {
            'status': -1,
            'success': 0,
        }
        if not all([username, email, password]):
            response['errmsg'] = '数据不完整'
            return JsonResponse(response)

        if len(password) < 6:
            response['errmsg'] = '密码必须6位以上'
            return JsonResponse(response)

        if not match('.{5,20}@(qq|163|126|gmail|sina|hotmail|icould).com', email):
            response['errmsg'] = '邮箱格式不正确'
            return JsonResponse(response)

        # if email.split('@')[1] == 'qq.com':
        #     qq = email.split('@')[1]
        #     import requests
        #     not_exist = requests.get(f'https://res.abeim.cn/api-qq?qq={qq}').text
        #     if not_exist:
        #         response['errmsg'] = 'QQ号不存在'
        #         return JsonResponse(response)

        from random import choices
        from celery_tasks.tasks import send_register_email_task

        code = ''.join(choices(settings.CODE_CHARS, k=6))
        send_register_email_task.delay(username, settings.EMAIL_FROM, email, code)

        request.session['code'] = code
        request.session.set_expiry(120)  # 验证码2分钟后过期

        response['status'] = 200
        response['success'] = 1
        return JsonResponse(response)


class RegisterView(View):
    @staticmethod
    def get(request):
        return render(request, 'user/register.html')

    @staticmethod
    def post(request):
        form_info = eval(request.body.decode('utf-8'))
        username = form_info.get('username')
        email = form_info.get('email')
        password = form_info.get('password')
        userinput_code = form_info.get('code')

        response = {
            'status': -1,
            'success': 0
        }

        if not all([username, password, email, userinput_code]):
            response['errmsg'] = '数据不完整'
            return JsonResponse(response)

        session_code = request.session.get('code')
        if not session_code:
            response['errmsg'] = '验证码不存在或已过期'
            return JsonResponse(response)

        if userinput_code != session_code:
            response['errmsg'] = '验证码不正确'
            return JsonResponse(response)

        # 核心业务处理
        try:
            MyUser.objects.get(username=username)
            response['errmsg'] = '用户名已存在'
            return JsonResponse(response)
        except MyUser.DoesNotExist:
            user = MyUser.objects.create_user(username=username, email=email, password=password)
            user.is_active = 1
            user.save()
            request.session.flush()  # 清除会话信息
            response['status'] = 200
            response['success'] = 1

        return JsonResponse(response)


class LoginView(View):
    @staticmethod
    def get(request):
        return render(request, 'user/login.html', {'forms': LoginForm()})

    @staticmethod
    def post(request):
        forms = LoginForm(request.POST)
        context = {
            'forms': forms,
        }
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if not user:
            context['errmsg'] = '用户不存在或密码错误'
            return render(request, 'user/login.html', context)

        login(request, user)
        next_url = request.GET.get('next', reverse('user:user'))
        print(next_url)
        return redirect(next_url)


class LogoutView(View):
    @staticmethod
    def get(request):
        logout(request)

        return redirect(reverse('goods:index'))


class UserCenterView(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        userinfo = MyUser.objects.get(id=request.user.id)
        context = {
            'active': 'userinfo',
            'userinfo': {
                'phone': userinfo.phone,
                'username:': userinfo.username,
                'introduce': userinfo.introduce,
                'balance': userinfo.balance,
                'email': userinfo.email,
            }
        }
        return render(request, 'user/user_center.html', context)

    def patch(self, request):
        form_info = eval(request.body.decode('utf-8'))
        response = {
            'success': 0,
            'status': -1
        }
        user = MyUser.objects.get(id=request.user.id)

        update_dict = {
            'email': self.update_email,
            'phone': self.update_phone,
            'introduce': self.update_introduce
        }

        update_key = list(form_info.keys())[0]

        error_message = update_dict[update_key](user, response, form_info)  # 修改不成功返回错误信息

        if error_message:
            response['errmsg'] = error_message
            return JsonResponse(response)

        user.save()

        response['status'] = 200
        response['success'] = 1

        return JsonResponse(response)

    @staticmethod
    def update_email(user, response, form_info):
        if not match('.{5,20}@(qq|163|126|gmail|sina|hotmail|icould).com', form_info.get('email')):
            return '邮箱格式不正确'
        user.email = form_info['email']

    @staticmethod
    def update_phone(user, response, form_info):
        if len(form_info['phone']) != 11 or not match('1[3-57-9][0-9]{9}', form_info['phone']):
            return '手机号格式不正确'
        user.phone = form_info['phone']

    @staticmethod
    def update_introduce(user, response, form_info):
        if not form_info.get('introduce'):
            return '内容不能为空'
        introduce = form_info['introduce']
        user.introduce = introduce


class BalanceView(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        user = MyUser.objects.get(id=request.user.id)
        context = {
            'active': 'balance',
            'total_recharge': user.total_recharge,
            'balance': user.balance,
            'total_consumption': user.total_consumption
        }
        return render(request, 'user/balance.html', context)


class AddressView(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        context = {
            'active': 'address',
            'delete': True,
            'update': True
        }
        return render(request, 'user/address.html', context)


class ModifyAddressView(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        """获取地址"""
        address = Address.objects.filter(user_id=request.user.id).order_by('-is_default')  # 默认地址放在第一个
        data = []
        for addr in address:
            data.append({
                'id': addr.id,
                'name': addr.recipient,
                'phone': addr.phone,
                'province': addr.province,
                'city': addr.city,
                'country': addr.country,
                'address': addr.detail_address,
                'is_default': addr.is_default
            })

        return JsonResponse({'data': data})

    @staticmethod
    def delete(request):
        """删除地址"""
        addr_id = request.body.decode('utf-8')
        response = {
            'res': 0,
            'status': -1
        }
        address = Address.objects.get(id=addr_id)
        if address.user_id != request.user.id:
            response['errmsg'] = '不能删除别人的地址'
            return JsonResponse(response)

        address.delete()
        response['res'] = 1
        response['status'] = 200
        response['msg'] = '地址删除成功'

        return JsonResponse(response)

    @staticmethod
    def post(request):
        """添加地址"""
        from json import loads
        form_data = loads(request.body.decode('utf-8'))

        recipient = form_data.get('name')
        phone = form_data.get('phone')
        province = form_data.get('province')
        city = form_data.get('city')
        country = form_data.get('country')
        detail_address = form_data.get('address')
        is_default = form_data.get('is_default')

        response = {
            'res': 0,
            'status': -1,
        }

        if not all([recipient, phone, province, city, country, detail_address]):
            response['errmsg'] = '请把数据填写完整'
            return JsonResponse(response)

        if is_default:
            default_address = Address.manager.get_user_default_address(request.user.id)
            if default_address:  # 把原来默认的地址设置成不默认
                default_address.is_default = False
                default_address.save()

        Address.objects.create(
            recipient=recipient,
            phone=phone,
            province=province,
            city=city,
            country=country,
            detail_address=detail_address,
            is_default=is_default,
            user_id=request.user.id
        )

        response['status'] = 200
        response['res'] = 1
        response['msg'] = '地址添加成功'

        return JsonResponse(response)

    @staticmethod
    def put(request):
        """修改地址"""
        from json import loads
        form_data = loads(request.body.decode('utf-8'))
        response = {
            'res': 0,
            'status': -1
        }
        try:
            address = Address.objects.get(id=form_data.get('id'))
        except Address.DoesNotExist:
            response['errmsg'] = '要修改的地址不存在，请重试'
            return JsonResponse(response)

        if address.user_id != request.user.id:

templates/user/address.html
{% extends 'user/user_center.html' %}

{% block menmber_title %}地址管理{% endblock menmber_title %}

{% block menmber %}
    {% include 'base_templates/base_address.html' %}
{% endblock menmber %}

templates/user/order_detail.html
{% extends 'user/user_center.html' %}

{% block title %} 订单详情 {% endblock %}

{% block menmber %}

<div class="box is-radiusless is-marginless pt-6" id="orderStatus">
    <b-steps v-model="activeStep" :has-navigation="false">
        <b-step-item label="待付款" icon="account-key" :clickable="false"></b-step-item>
        <b-step-item label="待发货" icon="car" :clickable="false"></b-step-item>
        <b-step-item label="待收货" icon="account-plus" :clickable="false"></b-step-item>
        <b-step-item label="待评价" icon="comment-plus" :clickable="false"></b-step-item>
        <b-step-item label="已完成" icon="store" :clickable="false"></b-step-item>
    </b-steps>
</div>

<div class="box is-radiusless is-marginless is-shadowless">
    <h1 class=" is-size-5">订单信息</h1>
    <div class="dropdown-divider"></div>
    <ul style="line-height: 30px;">
        <li>订单编号：{{ order.trade_no }}</li>
        
        <li>订单日期：{{ order.create_time }}</li>
        
        <li>支付状态：{{ order.pay_status }}</li>

        {% if order.status > 1 %}
            <li>支付方式：{{ pay_method }}</li>
        {% endif %}

        <li>订单金额：¥{{ order.total_price }}</li>

        <li>订单留言：{{ order.mark }}</li>
    </ul>
</div>
<div class="box is-radiusless is-marginless1 is-shadowless">
    <h1 class=" is-size-5">收货信息</h1>
    <div class="dropdown-divider"></div>
    <ul style="line-height: 30px;">
        <li>签收人：{{ address.recipient }}</li>
        <li>手机号：{{ address.phone }}</li>
        <li>收货地址：{{ address.province }}{{ address.city }}{{ address.country }}{{ address.detail_address }}</li>
    </ul>
</div>

<div class="box is-radiusless mb-4 is-shadowless">
    <h1 class=" is-size-5">商品信息</h1>
    <div class="dropdown-divider"></div>
    {% for goods_order in order.goods_orders %}
    <div class="is-flex is-justify-content-space-between">
        <div>
            <figure class=" image is-96x96">
                <img src="{{ goods_order.image }}" alt="{{ goods_order.name }}" srcset="">
            </figure>
        </div>
        <div class="has-background-danger1 is-flex is-flex-direction-column is-justify-content-center is-flex-grow-1 pl-3 pr-3">
            <h1 class="has-text-weight-bold">{{ goods_order.name }}</h1>
            <div class="is-flex">
                {% for option in goods_order.options %}
                <span class="mr-3 has-text-grey-light">{{ option.spec }}:{{ option.name }}</span>
                {% endfor %}
            </div>
        </div>
        <div class="has-background-danger1 is-flex is-justify-content-center is-align-items-center">
            <p class="has-text-danger-dark">¥ {{ goods_order.goods_dynamics.price }} x {{ goods_order.count }}</p>
        </div>
    </div>

    <div class="dropdown-divider"></div>
    {% endfor %}
    <div id="orderAction">
        <p class=" has-text-weight-bold pt-1 pb-1 has-text-right">共{{ order.total_count }}件商品，总金额{{ order.price }}元（含运费）</p>
        <div class=" buttons is-justify-content-end">
        {% if order.status == 1 %}
            <a class="button is-primary is-small" href="{% url 'order:pay' order.order_id %}">立即支付</a>
        {% elif order.status == 3 %}
            <button class="button is-primary is-small" @click="confirmProduct">确认收货</button>
        {% elif order.status == 4 and not is_commented %}
            <a class=" button is-primary is-small" href="{% url 'order:comment' order.order_id %}">立即评价</a>
        {% endif %}
        </div>
    </div>
</div>

{% endblock %}

{% block vue %}
<script>
    var orderStatus = new Vue({
        el: '#orderStatus',
        delimiters: ['{$', '$}'],
        data:{
            activeStep: 0,
        },
        created(){
            this.orderStatusMethod()
        },
        methods:{
            orderStatusMethod() {
                switch (Number('{{ order.status }}')) {
                    case 1:
                        this.activeStep = 0;
                        break;
                    case 2:
                        this.activeStep = 1;
                        break;
                    case 3:
                        this.activeStep = 2;
                        break;
                    case 4:
                        this.activeStep = 3;
                        break;
                    case 5:
                        this.activeStep = 4;
                        break;
                }
            },
        }
    })
</script>

<script>
    var confirmAction = new Vue({
        el: '#orderAction',
        delimiters: ['{$', '$}'],
        methods: {
            confirmProduct(){
                request({
                    url:'{% url "order:confirm" %}',
                    method: 'post',
                    data: {
                        order_id: {{ order.order_id }}
                    }
                }).then(res => {
                    if (res.data.status == 200) {
                        bayke.toastMessage('is-success', res.data.msg)
                        setTimeout(function(){location.reload()}, 2000)
                    }
                    else {
                        bayke.toastMessage('is-danger', res.data.errmsg)
                    }
                })
            }
        }
    })
</script>
{% endblock %}
    

templates/user/register.html
{% extends 'user/login.html' %}

{% load i18n %}

{% block title %}家电之选-注册{% endblock %}
{% block form-title %}注册{% endblock form-title %}

{# 继承login模板中的表单 #}
{% block form %}
<div id="register" class="pt-3">
    <b-field label="Username" :label-position="labelPosition">
        <b-input 
            maxlength="30"
            :has-counter="false"
            icon="account"
            v-model="username"
            placeholder="用户名">
        </b-input>
    </b-field>
    <b-field label="Password" :label-position="labelPosition">
        <b-input 
            type="password" 
            password-reveal
            :has-counter="false"
            maxlength="30"
            icon="lock"
            v-model="password"
            placeholder="密码">
        </b-input>
    </b-field>
    <b-field label="Email" :label-position="labelPosition" grouped group-multiline>
        <b-input 
            type="email" 
            :has-counter="false"
            maxlength="30"
            icon="email"
            v-model="email"
            @input="changeCode"
            expanded
            placeholder="邮箱">
        </b-input>
        <p class="control">
            <b-input 
                type="text" 
                maxlength="6"
                placeholder="验证码" 
                v-model="code" 
                :has-counter="false" 
                v-if="email" 
                expanded>
            </b-input>
        </p>
        <p class="control">
            <b-button class="button is-primary" :disabled="isshow" @click="getCode">{$ codetext $}</b-button>
        </p>
    </b-field>
    <b-field>
        <b-button 
            type="is-primary"
            @click="login" 
            expanded 
            :disabled="username && password && email && code ? false : true">
            注册
        </b-button>
    </b-field>
</div>
{% endblock form %}

{% block vue %}
    <script>
        var register = new Vue({
            el: '#register',
            delimiters: ['{$', '$}'],
            data:{
                labelPosition: 'on-border',
                code: '',
                username: '',
                password: '',
                email: '',
                codetext: '获取验证码',
                isshow: true,
                date: 60
            },
            methods: {
                changeCode(){
                    if (this.email){
                        this.isshow = false
                    }
                },
                getCode(){
                    request({
                        url: '{% url "user:send" %}',
                        method: 'post',
                        data: {
                            password: this.password,
                            username: this.username,
                            email: this.email
                        }
                    }).then(res => {
                        if (res.data.status === 200){
                            bayke.toastMessage('is-success', '验证码已发送，请前往邮箱查收！');
                        }
                        else {
                            bayke.toastMessage('is-danger', res.data.errmsg);
                        }
                    })
                },
                login(){
                    request({
                        url: '{% url "user:register" %}',
                        method: 'post',
                        data: {
                            username: this.username,
                            password: this.password,
                            email: this.email,
                            code: this.code
                        }
                    }).then(res => {
                        if (res.data.status === 200){
                            bayke.toastMessage('is-success', '注册成功，请登录！')
                            setTimeout(() => {
                                location.href = '{% url "user:login" %}'
                            }, 2000);
                        }else{
                            bayke.toastMessage('is-danger', res.data.errmsg)
                        }
                    })
                }
            },
        })
    </script>
{% endblock vue %}
    

templates/user/user_center.html
{% extends 'base_templates/base.html' %}

{% load static %}

{% block title %}{{ request.user.username }} - 个人中心{% endblock title %}

{% block breadcrumb %}
    <div class="container">
        <nav class="breadcrumb is-marginless mt-3 mb-3 is-small" aria-label="breadcrumbs">
            <ul>
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="is-active"><a href="{% url 'user:user' %}" aria-current="page">个人中心</a></li>
            </ul>
        </nav>
    </div>
{% endblock breadcrumb %}

{% block container %}
    <div class="container">
        <div class="columns">
            <div class="column is-2">
                <div class="box is-radiusless is-marginless is-flex is-flex-direction-column is-align-items-center">
                    <figure class="image is-64x64">
                        <img class="is-rounded" src="{{ request.user.image.url }}" alt="文件异常">
                    </figure>
                    <p class="mt-2">{{ request.user.username }}</p>
                    <div id="modify_img">
                        <input id="input_img" class="button is-primary is-small is-outlined" style="display: none"
                           type="file">
                        <button id="modify" class="button is-primary is-small is-outlined" style="margin-top: 10px"
                                @click="modify_image()">更换头像
                        </button>
                        <button type="submit" id="submit" class="button is-primary is-small is-outlined"
                                style="display: none; margin-top: 10px" @click="submit_image()">确认
                        </button>
                    </div>
                    <script>
                    var modify = new Vue({
                        el: '#modify_img',
                        methods: {
                            modify_image() {
                                var ele = document.getElementById('input_img');
                                ele.click();
                                ele.addEventListener("change", function () {
                                    // 隐藏更换头像按钮
                                    var modifyButton = document.getElementById("modify");
                                    modifyButton.style.display = "none";

                                    bayke.toastMessage('is-success', '文件上传成功！点击确认按钮以完成头像修改')

                                    // 显示提交按钮
                                    var submitButton = document.getElementById("submit");
                                    submitButton.style.display = "inline-block";
                                });
                            },
                            // 详见官方文档
                            getCookie(name) {
                                var cookieValue = null;
                                if (document.cookie && document.cookie !== '') {
                                    var cookies = document.cookie.split(';');
                                    for (var i = 0; i < cookies.length; i++) {
                                        var cookie = cookies[i].trim();
                                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                            break;
                                        }
                                    }
                                }
                                return cookieValue;
                            },
                            // 点击确认按钮
                            submit_image() {
                                var fileInput = document.getElementById("input_img");
                                var csrfmiddlewaretoken = getCookie('csrftoken');
                                var selectedFile = fileInput.files[0];

                                var formData = new FormData();

                                formData.append("image", selectedFile);
                                request({
                                    url: "{% url 'user:image' %}",
                                    method: 'post',
                                    data: formData,
                                    headers: {
                                        "X-CSRFToken": csrfmiddlewaretoken
                                    }
                                }).then(res => {
                                    if(res.status == 200) {
                                        bayke.toastMessage('is-success', '头像修改成功');
                                        setTimeout(() => {
                                            location.reload()
                                        }, 2000);
                                    }
                                    else {
                                        bayke.toastMessage('is-danger', res.data.errmsg);
                                    }
                                })
                            }
                        }
                    })
                </script>
                </div>
                <div class="box is-radiusless">
                    <aside class="menu">
                        <p class="menu-label">账户管理</p>
                        <ul class="menu-list">
                            <li><a href="{% url 'user:user' %}"
                                   class="{% if active == 'userinfo' %} is-active {% endif %}">个人信息</a></li>
                            <li><a href="{% url 'user:balance' %}"
                                   class="{% if active == 'balance' %} is-active {% endif %}">我的余额</a></li>
                            <li><a href="{% url 'user:address' %}"
                                   class="{% if active == 'address' %} is-active {% endif %}">地址管理</a></li>
                        </ul>
                        <p class="menu-label">订单管理</p>
                        <ul class="menu-list">
                            <li><a href="{% url 'user:my_order' 1 %}?sort=0"
                                   class="{% if active == 'order' %} is-active {% endif %}">我的订单</a></li>
                        </ul>
                    </aside>
                </div>
            </div>
            <div class="column">
                <div class="box is-radiusless">
                    <h1 class="is-size-4">
                        {% block menmber_title %}个人中心{% endblock %}
                    </h1>
                    <div class="dropdown-divider"></div>
                    {% block menmber %}
                        <div class="columns pt-3 pb-3">
                            <div class=" column is-2">个人信息</div>
                            {% include 'base_templates/userinfo.html' %}
                        </div>
                    {% endblock menmber %}
                </div>
            </div>
        </div>
    </div>
{% endblock container %}